version: "3.8"

services:
  db:
    image: postgres:14.2
    container_name: elixir_internal_certification_db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=elixir_internal_certification_dev
    ports:
      - "5432:5432"
